name: Unit Tests

permissions:
  contents: read
  actions: read

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  go-tests:
    name: Run Unit Tests
    strategy:
      matrix:
        go-version: ["1.23", "1.24"]
        platform: [ubuntu-latest]
      fail-fast: false

    runs-on: ${{ matrix.platform }}
    timeout-minutes: 10

    steps:
      - name: Check Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Restore Go Cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-

      - name: Run Tests
        env:
          TEST_COUNT: 1
          TEST_RACE_HISTORY_SIZE: 5
          TEST_TIMEOUT: 5m
          TEST_OPTS: ""
        run: make go-test

      - name: Debug on Failure
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@c606f8612a802e46b3742322514c09fbc8c4afee # v3.21
